---
kind: pipeline
name: develop

platform:
  os: linux
  arch: amd64

trigger:
  event:
    exclude:
      - pull_request
      - tag

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/bazarr
    cache_from: hotio/bazarr:develop
    build_args:
      - ARCH_BAZARR=none
    tags:
      - develop

---
kind: pipeline
name: release-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/bazarr
    cache_from: hotio/bazarr
    build_args:
      - ARCH_BAZARR=none
    tags:
      - ${DRONE_TAG}-linux-amd64

---
kind: pipeline
name: manifest

trigger:
  event:
    - tag

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: hotio/bazarr:latest
    template: hotio/bazarr:${DRONE_TAG}-OS-ARCH
    platforms:
      - linux/amd64

depends_on:
  - release-amd64
